// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://ptsdlumgkunklkxtsdfv.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InB0c2RsdW1na3Vua2xreHRzZGZ2Iiwicm9sZSI6ImFub24iLCJpYXQiOjE3NDQ2NDk4NTUsImV4cCI6MjA2MDIyNTg1NX0.Nm7NLOKR_4SnZrn8dcOpraZ7Z9cWu_fGkBpBjks0WEk";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY);